### ISSUE TITLE
option to have .here file override any other heuristics

### ISSUE THREAD

**Issue by swayson** [r-lib/here#21]
Some of the users with whom I collaborate with have complicated folder structures. We use .git for version control, some use RStudio and so the .rproj etc. can often result in the heuristics playing out in a inconsistent way. 

An option to have the .here file override any other heuristics would be a great way to solve this. 

Is this possible?

**Comment by swayson** [comment]
+1

**Comment by ML-StudyGroup** [comment]
+1

**Comment by adityabandla** [comment]
I am having the same issue. I typically track only my R scripts (using git) which reside in a folder under the root directory. When running R scripts from this folder, here seems to stop one it detects the .git and ignore the .here file in the parent folder

**Comment by ashander** [comment]
I ran into something similar when and took the advice in `?here()` to use more granular functions provided by rprojroot

>This package is intended for interactive use only.
> Use [rprojroot::has_file()] or the other functions in
> the \pkg{rprojroot} package for more control,
> or for package development.

**Comment by krlmlr** [comment]
Thanks. I'm reluctant to change the default criteria at this stage, using rprojroot looks like a good solution in those situations.

**Comment by krlmlr** [comment]
I added a link to the ["Getting started" article](https://here.r-lib.org/articles/here.html), feedback welcome.

**Comment by D3SL** [comment]
> Thanks. I'm reluctant to change the default criteria at this stage, using rprojroot looks like a good solution in those situations.

I might have been running into an edge case caused by something else but I thought obeying the `.here` file _was_ the default criteria. I don't know when that changed, or if this was never the intended behavior and I was just unreasonably lucky for a year and a half, but now this package is essentially unusable for me when making and testing dockerized shiny apps.

The problem is that the _project_ includes a parent folder full of docker build files and such that aren't copied over when the final image is built. Only the subfolder containing the app and all of its files and scripts gets copied over. 

As an example:

```
.
├── my_project1    //project root during development
         ├── .dockerignore
         ├── container_name.Rproj
         ├──  Dockerfile
         └── my_project2   //only this folder is copied to the docker image
                  ├── ui.r
                  ├── server.r
                  ├── global.r
                  ├── .here
                  └── data
                             └── data.csv
```

The project itself begins with `my_project1`, but when the docker image is built only `my_project2` will be copied over. `here()` allowed me to place a `.here` file in `my_project2` and make all of my code completely directory structure agnostic. Now I need to change every line of code back and forth between `here("my_project1", "data")` when developingand `here("data")` when building the final docker image, or abandon keeping all of the docker files as part of version control/project management.

To me this seems a lot more counterintuitive than the idea of ".here and it Just Works", and basically cripples the package for anyone who doesn't fit _exactly_ into the RStudio proprietary way of doing things
